version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Sarthak14
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_completed_successfully
    volumes: []
    environment:
      - DATABASE_URL=postgresql://postgres:Sarthak14@postgres:5432/postgres
      - NODE_ENV=development
    ports:
      - "3000:3000"